baseurl: "https://andysec.net/"
languageCode: en-us
theme: hello-friend
paginate: 5
publishDir: docs
params:
  contentTypeName: posts
  defaultTheme: dark
  showMenuItems: 2
  showReadingTime: true
languages:
  en:
    title: Andy Sec
    subtitle: A place for Andy to learn more about security
    keywords: ''
    copyright: ''
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    minuteReadingTime: min read
    dateFormatSingle: '2006-01-02'
    dateFormatList: '2006-01-02'
    params:
      logo:
        logoText: hello friend
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: showcase
          name: Showcase
          url: /showcase
